<div class="col-md-12 col-12" v-if="!showDatails ">
  <button type="submit" class="btn btn-primary left-0" @click="showDatails=true">
    بازگشت به لیست گزارشات ◄
  </button>
  <br>
  <hr>
  <table class="table table-bordered table-striped table-responsive-md">
    <thead>
    <tr>
      <th>نام</th>
      <th>وضعيت تاييد</th>
      <th>مدرك</th>
      <th>استان</th>
      <th>شهر</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>{{user.Name}}</td>
      <td>
        <button v-if="user.Validate==1" class="btn btn-outline-success">
          ✔
        </button>
        <button v-if="user.Validate==0" class="btn btn-outline-danger">
          ✘
        </button>
      </td>
      <td>
        <button v-if="user.Madrak==1" class="btn btn-outline-danger">
          زير ديپلم
        </button>
        <button v-if="user.Madrak==2" class="btn btn-outline-warning">
          ديپلم
        </button>
        <button v-if="user.Madrak==3" class="btn btn-outline-primary">
          كار داني
        </button>
        <button v-if="user.Madrak==4" class="btn btn-outline-success">
          كارشناسي
        </button>
        <button v-if="user.Madrak==5" class="btn btn-outline-success">
          كارشناسي ارشد
        </button>
        <button v-if="user.Madrak==6" class="btn btn-outline-info">
          دکتری
        </button>
        <button v-if="user.Madrak==7" class="btn btn-outline-secondary">
          فوق دکتری
        </button>
      </td>
      <td>
        <button v-if="user.Ostan==1" class="btn btn-outline-danger">
          اصفهان
        </button>
        <button v-if="user.Ostan==2" class="btn btn-outline-warning">
          تهران
        </button>
        <button v-if="user.Ostan==3" class="btn btn-outline-primary">
          شیراز
        </button>
        <button v-if="user.Ostan==4" class="btn btn-outline-success">
          قم
        </button>
        <button v-if="user.Ostan==5" class="btn btn-outline-success">
          مشهد
        </button>
        <button v-if="user.Ostan==6" class="btn btn-outline-info">
          همدان
        </button>
      </td>
      <td>{{user.Shaher}}</td>
    </tr>
    <tr>
      <th>جنسيت</th>
      <th>رشته</th>
      <th>ایمیل</th>
      <th colspan="2">تلفن</th>
    </tr>
    <tr>
      <td>
        <button v-if="user.Sex==1" class="btn btn-outline-primary">
          مرد
        </button>
        <button v-if="user.Sex==0" class="btn btn-outline-info">
          زن
        </button>

      </td>
      <td>{{user.Reshte}}</td>
      <td>{{user.Email}}</td>
      <td colspan="2">{{user.Phone}}</td>
    </tr>

    </tbody>
  </table>
</div>
<div class="container" v-if="!ShowEdit">
  <button type="submit" class="btn btn-primary left-0" @click="ShowEdit=true">
    بازگشت به لیست گزارشات ◄
  </button>

  <div id="Reg-mtn"> ویرایش کاربر</div>
  <div class="line-purple"></div>
  <form action="#" @submit.prevent="editUser()">

    <input type="hidden" v-model="Id=user.Id">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <label for="name">*
            نام و نام خانوادگی:
          </label>
          <input v-model="Name=user.Name"
                 type="text" class="form-control" id="name" placeholder="  نام و نام خانوادگی خود را وارد کنید  "
                 name="nam" required pattern=".{2,}"
                 oninvalid="setCustomValidity('وارد كردن نام و نام خانوادگي الزامي است.')"
                 oninput="setCustomValidity('')"
          >
        </fieldset>
      </div>
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <label for="rido">جنسیت:</label>
          <div id="rido" style="margin-right: 7%">
            <div class="btn btn-outline-primary  custom-control  custom-control-inline col-5  col-sm-4">
              <input type="radio" id="customRadioInline1" name="Sex" value="1"
                     class=" custom-control-input d-flex justify-content-center "
                     :checked="user.Sex==1" required
                     v-model="Sex=user.Sex"
              >
              <label class="custom-control-label" for="customRadioInline1">مرد</label>
            </div>
            <div class="btn custom-control  btn-outline-primary  custom-control-inline col-5 col-sm-4">
              <input type="radio" id="customRadioInline2"
                     name="Sex" value="2" class="custom-control-input"
                     :checked="user.Sex==2"
                     required
              >
              <label class="custom-control-label" for="customRadioInline2">زن</label>
            </div>
          </div>
        </fieldset>

      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <label for="Email">*
            آدرس ایمیل:
          </label>
          <input
              v-model="Email=user.Email"
              type="email" class="form-control" name="email" id="Email" placeholder="آدرس ایمیل خود را وارد کنید"
              required oninvalid="setCustomValidity('لطفا ايميل خود را به فرمت  example@example.com وارد كنيد.')"
              oninput="setCustomValidity('')"
          >
        </fieldset>
      </div>
      <div class="col-md-6 col-sm-12">
        <label for="inputEmail4">*
          شماره موبایل:
        </label>
        <input name="phone"
               v-model="Phone=user.Phone"
               type="tel" class="form-control" id="inputEmail4"
               placeholder=" شماره موبایل خود را وارد کنید :---------09"
               required pattern="[0-9]{11}"
               oninvalid="setCustomValidity('لطفا شماره تلفن همراه خود را به طور صحيح وارد كنيد')"
               oninput="setCustomValidity('')"

        >
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <label for="pas1">*
            رمز :
          </label>
          <input v-model="Password"
                 type="password" class="form-control" name="Pass" id="pas1" placeholder="رمز خود را وارد کنید"
                 required pattern=".{6,}" oninvalid="setCustomValidity('حداقل تعداد كاراكتر 6 كاراكتر مي باشد.')"
                 oninput="setCustomValidity('')">
        </fieldset>
      </div>
      <div class="col-md-6 col-sm-12">
        <label for="semat">*
          سمت:
        </label>
        <select class="custom-select my-1 mr-sm-2" id="semat" v-model="Semat=user.Semat" required name="Semat">
          <option value="0" :selected="user.Semat==0">کاربر عادی</option>
          <option :selected="user.Semat == 1" value="1">مدیر سایت</option>
        </select>
      </div>

    </div>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <label for="SelectPref">*
            استان :
          </label>
          <select class="custom-select my-1 mr-sm-2" id="SelectPref" required v-model="Ostan=user.Ostan" name="Ostan">
            <option value="1" :selected="user.Ostan == 1">اصفهان</option>
            <option value="2" :selected="user.Ostan == 2">تهران</option>
            <option value="3" :selected="user.Ostan == 3">شیراز</option>
            <option value="4" :selected="user.Ostan == 4">قم</option>
            <option value="5" :selected="user.Ostan == 5">مشهد</option>
            <option value="6" :selected="user.Ostan == 6">همدان</option>
          </select>
        </fieldset>
      </div>
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <label for="City">
            شهر :
          </label>
          <input type="text" class="form-control" id="City"
                 v-model="Shaher=user.Shaher"
                 name="Shaher"
                 placeholder="شهر محل سكونت خود را وارد كنيد   "

                 oninvalid="setCustomValidity('وارد كردن شهر الزامي نيست.')" oninput="setCustomValidity('')"
          >
        </fieldset>
      </div>

    </div>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <label for="madrak">*
            مدرك تحصيلي :
          </label>
          <select class="custom-select my-1 mr-sm-2" id="madrak" name="Madrak" v-model="Madrak=user.Madrak" required>
            <option value="1" :selected="user.Madrak == 1">زير ديپلم</option>
            <option value="2" :selected="user.Madrak == 2">ديپلم</option>
            <option value="3" :selected="user.Madrak == 3">كارداني</option>
            <option value="4" :selected="user.Madrak == 4">كارشناسي</option>
            <option value="5" :selected="user.Madrak == 5">كارشناسي ارشد</option>
            <option value="6" :selected="user.Madrak == 6">دكتري</option>
            <option value="7" :selected="user.Madrak == 7">فوق دكتري</option>
          </select>
        </fieldset>
      </div>
      <div class="col-md-6 col-sm-12">
        <fieldset>
          <fieldset>
            <label for="reshte">
              رشته ي تحصيلي :
            </label>
            <input type="text"
                   v-model="Reshte=user.Reshte"
                   name="Reshte" class="form-control" id="reshte"
                   placeholder="شهر محل سكونت خود را وارد كنيد" required
            >
          </fieldset>
        </fieldset>
      </div>
      <br><br><br>
      <br><br>
      <input type="submit" class="btn btn-success btn-block" value="ويرايش كاربر مورد نظر ">
    </div>
  </form>


  <!--  مودال-->


</div>
<div v-if="showDatails && ShowEdit">
  <table class="table table-bordered table-striped table-responsive-md">
    <thead>
    <tr>
      <th>شناسه</th>
      <th>نام</th>
      <th>ايميل</th>
      <th>وضعيت تاييد ايميل</th>
      <th>عمليات</th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="(user,index) in Users">
      <td>{{index+1}}</td>
      <td>{{user.Name}}</td>
      <td>{{user.Email}}</td>
      <td>
        <button v-if="user.Validate==1" class="btn btn-success">
          ✔
        </button>
        <button v-if="user.Validate==0" class="btn btn-danger">
          ✘
        </button>
      </td>
      <td>

        <a class="btn btn-info" @click.prevent="User($event,'datails')" :href="index">
          جزئيات بيشتر
        </a>
        <a class="btn btn-primary" @click.prevent="User($event,'edit')" :href="index">
          ويرايش
        </a>
        <a class="btn btn-danger" @click.prevent="User($event,'remove')" :href="index">
          حذف
        </a>

      </td>
    </tr>

    </tbody>
  </table>
</div>
