<div class="col-md-12 col-12" v-if="!showDatails">
  <button type="submit" class="btn btn-primary left-0" @click="showDatails=true" >
    بازگشت به لیست گزارشات ◄
  </button>
  <br>
  <hr>
  <table class="table table-bordered table-striped table-responsive-md">
    <thead>
    <tr>
      <th colspan="3">ديدگاه</th>
      <th>ایمیل کاربر</th>
      <th>نام كاربر</th>
      <th>تاريخ ارسال</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td colspan="3">{{comment.comment_co}}</td>
      <td>{{comment.Email_co}}</td>
      <td>{{comment.Name_co}}</td>
      <td>{{comment.Tarihk_co}}</td>
    </tr>
    <tr>
   <th>شناسه</th>
   <th colspan="2">متن ريپلاي</th>
   <th>تاريخ</th>
   <th>نام پاسخ دهنده</th>
   <th>عمليات</th>
    </tr>
      <td colspan="6"  v-if="comment.Rep==''">
        برای این دیدگاه هیچ پاسخی وجود ندارد.
      </td>
    <tr v-for="(item,index) in comment.Rep">
      <td>
        {{index+1}}
      </td>
      <td colspan="2">
        {{item.comment_rep}}
      </td>
      <td>
        {{item.Tarihk_rep}}
      </td>
      <td>
        {{item.Name_rep}}
      </td>
      <td>
        <a class="btn btn-danger" href="#">حذف</a>
      </td>

    </tr>
    </tbody>
  </table>

     <span >


<!--       <td>{{item.comment_rep}}</td>-->

     </span>
</div>
<!---->
<div v-if="showDatails">
  <table class="table table-bordered table-striped">
    <thead>
    <tr>
      <th></th>
      <th>نام كاربر</th>
      <th >ايميل</th>
      <th>عمليات</th>
    </tr>
    </thead>
    <tbody>
    <tr v-for="(comment,index) in getThePage()">
      <td>{{index+1+adding}}</td>
      <td>
        {{comment.Name_co}}
      </td>
      <td>
        {{comment.Email_co}}
      </td>
      <td>
          <a class="btn btn-info"   @click.prevent="Comm($event,'details')" :href="index+adding">جزئيات</a>
          <a class="btn btn-primary" @click.prevent="Comm($event,'ans')" :href="index+adding">پاسخ به ديدگاه</a>
        <a class="btn btn-danger" @click.prevent="Comm($event,'delete')" :href="index+adding">حذف ديدگاه</a>
      </td>
    </tr>
    </tbody>
  </table>

  <div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" @click.prevent="Previous()" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <span v-for="n in paginationComments()">
        <li class="page-item"><button :class="isActive(n)" @click.prevent="ThePage(n)">{{n}}</button></li>
        </span>
        <li class="page-item">
          <a class="page-link" href="#"  @click.prevent="Next()" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>
