<div class="container content">
  <a href="#" id="contact-link">تماس با ما</a>
  <div class="trapezoid  btn-center">
    <img src="./asetes/img/logo_bw.svg" width="75px">
  </div>
  <hr style="background-color: #683795;">
  <div class="mtn-cont">
    <p id="head-of-cont">وب سایت «ای-استخدام» معتبرترین سامانه آگهی های استخدامی سراسر کشور</p>
    <div>
      <img src="./asetes/img/e-es.png" alt="" class="icon2">
      <span class="mtn-jadval">
        پشتیبانی و مشاوره درج آگهی کارفرمایان
      </span>
      <div class="mostatil">
        <p class="mtn-vasat">در صورتی که قصد درج آگهی استخدام یا تغییرات در متن آگهی خود را دارید با شماره زیر تماس
          بگیرید</p>
      </div>
      <div class="mostatil-2">
        <p class="mtn-vasat-red">
          زمان پاسخگویی تلفنی : شنبه تا چهارشنبه از ساعت ۸ الی ۱۷ و پنجشنبه ها از ساعت ۸ الی ۱۶
        </p>
        <div class="mostatil-md-blue">

          <div class="moraba-blue">
            <a href="tel://۰۲۱-۴۴۲۹۱۸۴۴" id="phone-number">۰۲۱-۴۴۲۹۱۸۴۴</a>
            <img src="./asetes/img/tele.ico" alt="" style="padding: 15%">
          </div>

        </div>
        <div class="mostatil-md-blue">
          <div class="moraba-blue">
            <img src="./asetes/img/email.png" alt="" style="padding: 15%;width: 50px">
            <a href="mailto:ads@e-estekhdam.com" target="_blank" id="email-cont" style="width: 400px">ads@e-estekhdam.com</a>
          </div>
        </div>
        <div class="mostatil-md-purple">

          <div class="moraba-purple">
            <img src="./asetes/img/link.png" alt="" style="padding: 15%;width: 50px">
            <a href="#" style="width: 400px" id="es-req-cont"> برای درج آگهی استخدام اینجا کلیک کنید</a>
          </div>
        </div>
      </div>
    </div>
  </div>
 <br>
  <div class="mtn-cont">
    <div>
      <img src="./asetes/img/e-es.png" alt="" class="icon2">
      <span class="mtn-jadval">
        پشتیبانی کارجویان
      </span>
      <div class="mostatil">
        <p class="mtn-vasat">در صورتی که سوالی در زمینه دریافت آگهی های استخدامی یا سوالات آزمون دارید با شماره های زیر
          تماس بگیرید</p>
      </div>
      <div class="mostatil-2">
        <p class="mtn-vasat-red">
          زمان پاسخگویی تلفنی : شنبه تا پنج شنبه از ساعت ۸ الی ۱۶
        </p>
        <div class="mostatil-md-blue">

          <div class="moraba-blue">
            <a href="tel://۰۲۱-۴۴۲۹۱۸۴۴" id="phone-number">۰۲۱-۴۴۲۹۱۸۷۴</a>
            <img src="./asetes/img/tele.ico" alt="" style="padding: 15%">
          </div>


        </div>
        <div class="mostatil-md-blue">
          <div class="moraba-blue">
            <img src="./asetes/img/tele.ico" alt="" style="padding: 15%">
            <a href="tel://۰۲۱-۴۴۲۹۱۸۴۴" id="phone-number">۰۲۱-۴۴۲۹۱۰۱۵</a>
          </div>
        </div>
        <div class="mostatil-md-blue">
          <div class="moraba-blue">
            <img src="./asetes/img/email.png" alt="" style="padding: 15%;width: 50px">
            <a href="mailto:info@e-estekhdam.com" target="_blank" id="email-cont" style="width: 400px">info@e-estekhdam.com</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="mtn-cont">
    <div>
      <img src="./asetes/img/e-es.png" alt="" class="icon2">
      <span class="mtn-jadval">
        ارتباط مستقیم با مدیریت
      </span>
      <div class="mostatil" style="height: 80px">
        <div class="mostatil-md-blue" style="margin-top: 10px">
          <div class="moraba-blue">
            <img src="./asetes/img/email.png" alt="" style="padding: 15%;width: 50px">
            <a href="mailto:admin@e-estekhdam.com" target="_blank" id="email-cont" style="width: 400px">admin@e-estekhdam.com</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="mtn-cont">
    <div class="mostatil-zard">
      <img src="./asetes/img/danger.png" id="danger_png" style="margin-right: 48%;margin-top: 5px" alt="#">
    <div class="mostatil-sefid">
    <p>
      شماره پیامکی وب سایت «ای-استخدام»
      <span style="color: #ba1842">۲۰۰۰۰۶۱۸</span>
      و
      <span style="color: #ba1842"> ۱۰۰۰۰۶۱۸</span>
      میباشد بدیهی است فقط مسئولیت این شماره با ما میباشد و هیچ شماره پیامکی دیگری مورد تایید و متوجه «ای-استخدام» نیست.
    </p>
    </div>
    </div>
  </div>

</div>
<br><br><br><br><br>