<?php
require_once "./model/editResume.php";
?>
<?php  $this->loadView('MenoUser'); ?>
<div class="row">
<div class="col-4">
  <?php $this->loadView('panelUserMeno')
  ?>

</div>

<div id="edit_resume" class="col-md-8">
    <div id="edit_resume_title" class="editforresume_title row">
        <h3>
            تکمیل رزومه
        </h3>
    </div>

    <div id="resume" class="for_resume">
        <div id="base_infromation" class="user_information">
            <div id="base_information_title">
                <div class="row">
                    <span class="resume_first_span">
                    <i class="fa fa-pencil"></i>
                </span>
                    <h3>
                        اطلاعات پایه
                    </h3>
                    <a href="./panelUser_editUserInfo" class="edit_info">
                    <span class="resume_seccond_span">
                    <i class="fa fa-pencil fa_sec"></i>
                    ویرایش
                    </span>
                    </a>

                </div>
            </div>
            <div id="base_information_body">
                <div id="base_body_name">
                    <h3>
                        فوو
                    </h3>
                    <div>
                        <a class="for_dec" href="./panelUser_editUserInfo">
                            <i class="fa fa-plus"></i>
                            عنوان حرفه ای اضافه کنید
                        </a>
                    </div>
                    <div class="user_for">
                        <a href="PanelUser_editEmail" id="">
                            <i class="fa fa-pencil"></i>
                            <?= $_SESSION["logIn"];?>
                        </a>
                    </div>
                    <div class="user_for">
                        <p>شماره تلفن</p>
                    </div>
                    <div class="user_for">
                        <p>شهر</p>
                    </div>
                </div>
            </div>
            <div id="base_information_footer">
                <div class="us_info_1">
                    <div class="user_info_first">
                        <div class="row">
                            <p class="user_info_p">
                                جنسیت:
                                <b>مرد</b>
                            </p>
                            <p class="user_info_p">
                                وضعیت تاهل:
                                <b>-</b>
                            </p>
                        </div>
                    </div>
                    <div class="user_info_first">
                        <div class="row">
                            <p class="user_info_p">
                                سربازی:
                                <b>-</b>
                            </p>
                            <p class="user_info_p">
                                متولد:
                                <b>-</b>
                            </p>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <div id="jobInfo" class="for_resume">
        <div id="jobInformation" class="user_information">
            <div id="job_information_title">
                <div class="row">
                    <span class="resume_first_span">
                    <i class="fa fa-briefcase"></i>
                </span>
                    <h3>
                        اطلاعات شغلی
                    </h3>
                    <a href="./panelUser_jobInfo" class="edit_info">
                    <span class="resume_seccond_span">
                    <i class="fa fa-pencil fa_sec"></i>
                    ویرایش
                    </span>
                    </a>

                </div>
            </div>
            <div id="job_information_footer">
                <div class="us_info_1">
                    <div class="user_info_first">
                        <div class="row">
                            <p class="user_info_p">
                                وضعیت اشتغال:
                                <b><?= $job_status;?></b>
                            </p>
                        </div>
                    </div>
                    <div class="user_info_first">
                        <div class="row">
                            <p class="user_info_p">
                                آماده کار در:
                                <b><?= $work_in;?></b>
                            </p>
                            <p class="user_info_p">
                                حداقل حقوق درخواستی:
                                <b><?= $salary;?></b>
                            </p>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

    <div id="languageInfo" class="for_resume">
        <div id="lanInformation" class="user_information">
            <div id="lan_information_title">
                <div class="row">
                    <span class="resume_first_span">
                    <i class="fa fa-language"></i>
                </span>
                    <h3>
                       زبان ها خارجی
                    </h3>
                    <a href="./panelUser_other?action=language" class="edit_info">
                    <span class="resume_seccond_span">
                    <i class="fa fa-plus fa_sec"></i>
                    افزودن
                    </span>
                    </a>

                </div>
            </div>
            <div id="job_information_footer">
                <div class="us_info_1">
                    <div class="user_info_first">
                        <div class="row">
                            <?php
                            $languages = explode("-",$languages);
                            $languages_level = explode("-",$languages_level);
                            for ($i=0;$i<count($languages)-1;$i++){
                                $img="./asetes/img/cv_".$languages_level[$i].".svg";
                                echo " 
                                      <div class=\"user_info_p\">
                                      <center>
                                      <img class='img_lan' src=$img alt=''>
                                      <p>$languages[$i]</p>
                                      </center>
                                      </div>
                                      
                                ";
                            }
                            ?>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>

</div>

