<?php
require_once "./model/editUsergmail.php";
?>
<div class="row">
  <div class="col-4">
      <?php $this->loadView('panelUserMeno') ?>
  </div>
  <div id="editUserEmail" class=" col-8">

    <div id="edit_resume_title">
      <a href="./panelUser_editResume" id="a_edit_info">
        <i class="fa fa-arrow-right"></i>
      </a>
      <h3>
        اصلاح آدرس ایمیل
      </h3>
    </div>

    <div id="editemail_alert" class="row">
        <span id="editemailspan">
            <i class="fa fa-bell"></i>
        </span>
      <div id="editemailp">
        <p>شما با آدرس ایمیل <?php echo $email; ?> در سایت «ای استخدام» عضو هستید، در صورت تمایل میتوانید آدرس ایمیل خود
          را تغییر دهید
        </p>
        <p>• با تغییر آدرس ایمیل فوق مشخصات ورود و ایمیل ذکر شده در رزومه شما با آدرس جدید جایگزین میشود</p>
      </div>

    </div>

    <div id="ed_mail">
      <div id="newemail">
        <div class="newmail">
          <label>آدرس جدید ایمیل خود را وراد کنید</label>
          <div id="new_email_first_input" class="row new_email_first_input">
                <span class="a_sign">
                    @
                </span>
            <input type="text" id="new_email_input" class="new_email_input">
          </div>
        </div>

        <div class="newmail">
          <label>آدرس جدید ایمیل خود را تکرار کنید</label>
          <div id="new_email_first_input" class="row new_email_first_input">
                <span class="a_sign">
                    @
                </span>
            <input type="text" id="new_sec_email_input" class="new_email_input">
          </div>
        </div>

        <center>
          <button id="sub_ed_email">
            ثبت
          </button>
        </center>
      </div>
    </div>
  </div>

</div>