<div id="es_sarasari_info">
    <div class="col-md-12 row" id="es_sa_info">
        <div class="col-md-10" id="es_sa_info_infos">
            <?php
            include "./model/es_sarasari.php";
            ?>
            <div id="es_sa_info_infos_first">

            </div>
        </div>
        <div class="col-md-2" id="ese_sa_info_more">
            <div class="col-md-12 es_ser_mors">
                <i class="fa fa-share"></i>
                <span>|</span>
                <span>اشتراک گذاری</span>
            </div>
            <div class="col-md-12 es_ser_mors">
                <a href="adver">
                    <i class="fa fa-search"></i>
                    <span>|</span>
                    <span>جستجو در آگهی ها</span>
                </a>
            </div>
            <div class="col-md-12 es_ser_mors">
                <a href="taghvim">
                    <i class="fa fa-calendar"></i>
                    <span>|</span>
                    <span>تقویم استخدام</span>
                </a>
            </div>
            <div class="col-md-12 es_ser_mors">
                <a href="dargeAgahi">
                    <i class="fa fa-pencil"></i>
                    <span>|</span>
                    <span>درج آگهی استخدام</span>
                </a>
            </div>
        </div>
    </div>
</div>