<div id="estekhdam_sarasari">
    <div class="col-md-12 row" id="es_sa">
        <div class="col-md-10 row">
            <div class="col-md-12" id="estekhdam_saari_title">
                <h3 id="h3_es">استخدام های سراسری</h3>
            </div>
            <div class="col-md-12 row" id="advers_sar">
                <?php
                include './model/estekhdamSarasari.php';
                ?>
            </div>

        </div>


        <div class="col-md-2" id="es_sar_mor">
            <div class="col-md-12 es_ser_mors">
                <i class="fa fa-share"></i>
                <span>|</span>
                <span>اشتراک گذاری</span>
            </div>
            <div class="col-md-12 es_ser_mors">
                <a href="adver">
                    <i class="fa fa-search"></i>
                    <span>|</span>
                    <span>جستجو در آگهی ها</span>
                </a>
            </div>
            <div class="col-md-12 es_ser_mors">
                <a href="taghvim">
                    <i class="fa fa-calendar"></i>
                    <span>|</span>
                    <span>تقویم استخئدام</span>
                </a>
            </div>
            <div class="col-md-12 es_ser_mors">
                <a href="dargeAgahi">
                    <i class="fa fa-pencil"></i>
                    <span>|</span>
                    <span>درج آگهی استخدام</span>
                </a>
            </div>
        </div>
    </div>

</div>