<div id="foot">
    <div id="footer" class="row">
        <div class="col-md-2" id="footer_first">
            <ul>
                <li><a class="foot_inf" href="<?php View::GoTo('Home') ?>"> <i class="fa fa-angle-left"></i><span class="foot_span">خانه</span> </a> </li>
                <li><a class="foot_inf" href="<?php View::GoTo('signup') ?>"> <i class="fa fa-angle-left"></i><span class="foot_span">ثبت نام</span> </a> </li>
                <li ><a class="foot_inf" href="<?php View::GoTo('vorod') ?>"> <i class="fa fa-angle-left"></i><span class="foot_span" >ورود کاربران</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">راهنمای پرداخت آنلاین</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">ورود کارفرمایان</span> </a> </li>
                <li><a class="foot_inf" href="<?php View::GoTo('contact') ?>"> <i class="fa fa-angle-left"></i><span class="foot_span">تماس باما</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">درباره باما</span> </a> </li>
            </ul>
        </div>
        <div class="col-md-2" id="footer_second">
            <ul>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">درج آگهی استخدام</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">اخبار استخدامی</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">استخدام های سراسری</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">استخدام های بانک ها</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">استخدام های تهران</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">استخدام های استان ها</span> </a> </li>
                <li><a class="foot_inf" href="#"> <i class="fa fa-angle-left"></i><span class="foot_span">دانلود سوالات استخدامی</span> </a> </li>
            </ul>
        </div>
        <div class="col-md-4" id="footer_third">
            <p class="footer_info">
                تمامی کالاها و خدمات این فروشگاه، حسب مورد دارای مجوزهای لازم از مراجع مربوطه می‌باشند و فعالیت‌های این سایت تابع قوانین و مقررات جمهوری اسلامی ایران است.
            </p>
            <p class="footer_info">این وب سایت در سامانه ساماندهی به آدرس <a href="www.samandehi.ir">www.samandehi.ir</a> ثبت گردیده است.</p>
        </div>
        <div class="col-md-2" id="footer_forth">
            <p class="footer_info"><a href="#"><i class="fa fa-download"></i><span class="foot_span">دانلود اپ با لینک مستقیم</span></a></p>
            <hr class="footer_hr">
            <p class="footer_info"><a href="#"><i class="fa fa-google"></i><span class="foot_span">دانلود اپ از گوگل پلی</span></a></p>
            <hr class="footer_hr">
            <p class="footer_info"><a href="#"><i class="fa fa-shopping-basket"></i><span class="foot_span">دانلود اپ از کافه بازار</span></a></p>

        </div>
        <div class="col-md-2" id="footer_fifth">
            <p><i class="fa fa-phone"></i><span class="foot_span"> پشتیبانی آگهی‌دهندگان
            44291844(021)</span></p>
            <p><i class="fa fa-phone"></i>
                <span class="foot_span">پشتیبانی کاربران
            44291874 (021)
            44291015 (021)</span></p>
            <img src="<?php Assetes::img('enamad2.png') ?>" alt="">

        </div>
        <div class="col-md-12" id="footer_sixth">
            <p>تمامی حقوق این وبسایت متعلق به سامانه «ای-استخدام» میباشد و استفاده از مطالب همراه با ذکر منبع بلا مانع است.</p>
        </div>
    </div>

</div>
