<div class="UserShowMenu itsMenuProfileOfUser">
  <div class="MenuUserProfile">
    <div class="listOfMenuUserProfile">
      <ul>
        <a href="PanelUser_index">
        <li>
          <img src="./asetes/img/homeforPanel.png" class="icon2" alt="">
          <span>          پیشخوان
          </span>
        </li>
        </a>
        <a href="./PanelUser_editResume">
          <li>
            <img src="./asetes/img/cv.png" class="icon2" alt="">
            <span>
          رزومه
          </span>
          </li>
        </a>
        <a href="#">
          <li>
            <img src="./asetes/img/star.png" class="icon2" alt="">
            <span>
          لیست نشان دار شده ها
          </span>
          </li>
        </a>
        <a href="./PanelUser_userAdvertise">
          <li>
            <img src="./asetes/img/editeIist.png" class="icon2" alt="">
            <span>
          تصحیح اگهی
          </span>
          </li>
        </a>
        <a href="./Out">
          <li>
            <img src="./asetes/img/exit.png" class="icon2" alt="">
            <span>
          خروج
          </span>
          </li>
        </a>
      </ul>
    </div>
  </div>
</div>