<div v-if="zabdargo"  style="width: 1200px">
  <div class="Modal-backdrop" @click="Zago=0">
  </div>
  <div id="modal" >
    <div id="narengi-header">
      <b>
        گزارش مشكل
        <a href="#" class="linkWithOutUnderLine" style="float: left;margin-left:5px" @click="Zago=0">
          &times;
        </a>
      </b>
    </div>


    <form action="#" method="post">

      <div class="row">
        <div class="col-1"></div>
        <div class="col-9">
          <label for="mtn-er">* شماره تلفن شما (جهت پيگيري)</label>
          <input type="text" class="form-control " id="mtn-er" placeholder=" شماره تلفن خود را وارد كنيد. "
                 required>
          <label for="email-er"> ايميل شما (جهت پيگيري)</label>
          <input type="text" class="form-control " id="email-er" placeholder=" ايميل خود را وارد كنيد. ">
          <label for="text-er">* توضيحات </label>
          <textarea class="form-control " rows="5" cols="30" id="text-er"
                    placeholder=" متن مورد نظر خود در اينجا وارد كنيد" required></textarea>
          <input type="submit" class="btn btn-success" value="ثبت اشكال" style="margin-right: 40%;">
        </div>
        <div class="col-2"></div>
      </div>
    </form>
  </div>
</div>