<div id="es_sa_info_infos_title">
    <h4 id="es_sa_info_infos_title_h4">
        <?= $adv_title ?>
    </h4>
</div>
<div id="adv_extra_infs" class="row">
    <p id="adv_extra_inf_day">
        انتشار در
        <?= $day ?>
        <?= $mo ?>
        <?= $year ?>
    </p>
    <p id="adv_extra_inf_today">
        <?= $when ?>
    </p>
    <p id='adv_admin'>
        مدیر
    </p>
</div>
<div id="es_sa_info_infos_second_title">
    <center>
        <h4 id="es_sa_info_infos_second_title_h4">
            <?= $adv_second_titlle ?>
        </h4>
    </center>
</div>
<div class="es_sa_info_infos_first">
  <?= $Options ?>
</div>