<div >
    <div>
        <form action="#" method="post">
            <label for="tiket">عنوان تيكت</label>
            <input type="text" class="form-control" id="tiket" name="tiket_name">
            <label for="tiket_point">ميزان اهميت</label>
            <select class="custom-select" id="tiket_point"  aria-label="Default select example">
                <option selected>Open this select menu</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>

        </form>
    </div>
</div>