<div id="user_advertise">
    <div class="row ">
         <div class="col-md-3 col-2">

                    <?php $this->loadView('panelUserMeno')?>

        </div>
        <div class="col-lg-9 col-md-9 col-10 " >
            <div id="user_advertises">
                <div id="user_advertise_title">
                    <h3>مدیریت آگهی</h3>
                </div>

                <div id="user_advertises_info">
                    <span id="span_seccond"><i class="fa fa-bell"></i></span>
                    <span>از پنل پایین میتوانید آگهی های خوذ را حذف و یا ویرایش کنید</span>
                </div>

                <div id="user_advertises_pannel">
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <td style="width: 10%">ردیف</td>
                            <td style="width: 70%">عنوان آگهی</td>
                            <td style="width: 10%">ویرایش</td>
                            <td style="width: 10%">حذف</td>
                        </tr>
                        </thead>
                        <tbody id="user_advertise_tbody">
                        <?php
                        include "./model/user_advertise.php";
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>