<div class="container">
    <div class="validationReg">
      ايميلي براي تاييد به ايميل شما ارسال شده است لطفا ايميل خود را تاييد كنيد .
      لازم به ذكر است درصورتي كه ايميل خود را تاييد نكنيد به پنل كاربري دسترسي نخواهيد داشت.
      <img src="./asetes/img/alarm.png" class="inPadding" alt="">
      <br>
      <div class="d-flex justify-content-center">
<!--      <button class="btn  btn-danger " style="margin-top: 10px"> ارسال دورباره تاييديه ايميل</button>-->
      </div>
    </div>
</div>
